# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Fetch 10Gen signing key
  become: yes
  apt_key: keyserver=keyserver.ubuntu.com id=EA312927

- name: Add mongo sources list
  become: yes
  lineinfile: >
    line="deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse"
    dest=/etc/apt/sources.list.d/mongodb.list
    state=present
    create=yes

- name: Install mongo
  become: yes
  apt: name=mongodb-org state=latest update_cache=yes

- name: Ensure daemon is running
  service: name=mongod state=started

- name: Create the directory
  file: path="{{ data_dir }}" state=directory mode=0755

- name: Copy projects.json file
  copy: src="{{ copy_dir }}/{{ projects_file_name }}" 
        dest="{{ data_dir }}/{{projects_file_name }}" 
        owner="{{ owner }}" 
        group="{{ group }}" 
        mode=0644
  sudo: yes

- name: Create Project collections
  shell: mongo dcc-import --eval "db.createCollection('Project')"

- name: Load projects.json into Project collection
  command: mongoimport --db dcc-import --collection Project --jsonArray --file {{ data_dir }}/{{ projects_file_name }}
