# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

# - include: tasks/setup.yml group=hadoop-master:hadoop-worker:id-group:etl
# - include: tasks/setup-existing.yml group=hadoop-master:hadoop-worker:id-group:etl

# HDFS - Namenode
- hosts: hadoop-master
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - { role: hdfs, hdfs_namenode: True }

# HDFS - Datanode    
- hosts: hadoop-worker
  become: yes
  vars_files:
  - "vars/main.yml"
  roles:
    - { role: hdfs, hdfs_namenode: False }


# Spark - Master
- hosts: hadoop-master
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - { role: spark, master: True }

# Spark - Slave    
- hosts: hadoop-worker
  become: yes
  vars_files:
  - "vars/main.yml"
  roles:
    - { role: spark, master : False }

# Id Postgres Server
# - name: Provision download server with postgres
#   hosts: id_server
#   gather_facts: no
#   become: yes
#   vars_files:
#     - "vars/main.yml"
#   roles:
#     - postgres

- name: Provision Mongodb server
  hosts: etl
  gather_facts: no
  become: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - mongodb

- name: Start Fathmm Postgres server
  hosts: hadoop-master
  become: yes
  gather_facts: no
  vars_files:
  - "vars/main.yml"
  roles:
    - postgresql

- name: Prep Fathmm server
  hosts: hadoop-master
  become_user: postgres
  gather_facts: no
  vars_files:
  - "vars/main.yml"
  roles: 
    - fathmm

- name: Provision Import and Release
  hosts: etl
  gather_facts: no
  become: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - import
    - release
