# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

# - include: tasks/setup.yml group=hdfs-namenode:hdfs-datanode
# - include: tasks/setup-existing.yml group=hdfs-namenode:hdfs-datanode

# HDFS - Namenode
- hosts: dcc-etl-test
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - { role: hdfs, hdfs_namenode: True }
