- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: ensure packages are installed
  apt: name={{ item }}
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Ensure directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ data_dir }}"

- name: Download Fathmm dataset
  get_url: url="{{ fathmm_dataset_url }}"
           dest="{{ data_dir }}/{{ fathmm_dataset_name }}"
           mode=0444
  become: yes

- name: Extract the dataset
  unarchive: src="{{ data_dir }}/{{ fathmm_dataset_name }}"
             dest="{{ data_dir }}"
             copy=no

#- name: Check if Fathmm dataset is already downloaded
#  command: test -e {{ etl_home }}/{{ fathmm_dataset_name }}
#  register: find_result
#  ignore_errors: yes
#
#- include: download_fathmm.yml
#  when: find_result != 0
