- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: ensure packages are installed
  apt: name={{ item }}
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Check if Fathmm dataset is already downloaded
  command: test -e {{ etl_home }}/{{ fathmm_dataset_name }}
  register: find_result
  ignore_errors: yes

- include: download_fathmm.yml
  when: find_result != 0
