- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: ensure packages are installed
  apt: name={{ item }}
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Ensure directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ data_dir }}"

- name: Download Fathmm dataset
  get_url: url="{{ fathmm_dataset_url }}"
           dest="{{ data_dir }}/{{ fathmm_dataset_tar }}"
           mode=0444
  become: yes

- name: Check if Fathmm dataset is already extracted
  command: test -e {{ data_dir }}/{{ fathmm_dataset }}
  register: find_result
  ignore_errors: yes

- name: Check if dataset patch exists
  command: test -e {{ data_dir }}/{{ fathmm_dataset_patch }}
  register: find_result_patch
  ignore_errors: yes

- include: extract_fathmm.yml
  when: find_result.rc != 0 or find_result_patch.rc != 0
