- name: Ensure database is created
  postgresql_db: name={{ dbname }}

- name: Ensure user has access to database
  postgresql_user: db={{ dbname }} name={{ dbuser }} password={{ dbpassword }} priv=ALL

- name: Upload dataset to postgres
  command: psql fathmm < {{ etl_home }}/{{ fathmm_dataset_name }}
